### ISSUE TITLE
questions about features supported by pyBK

### ISSUE THREAD

**Issue by shubhamshukla7** [josepatino/pyBK#4]
Hi there - I am new to Speaker Diarization and was exploring the repo as I have a few questions. I looked at the diarization demo provided in the README and here are my questions:

**Use live audio stream instead of statis audio files:**
I see that the demo uses a static audio file although in my use-case, I will be working with a realtime audio stream. Does pyBK support streaming input for speech diarization? If so, is there somewhere I could find some resource/sample code to look into for reference?

**Number of speakers unknown in the beginning of the audio stream.**
Unlike in usual diarization models where the numbers of speakers is usually known, in my usecase,  I will be trying to stream audio from a live meetings which means that the total number of users might not be known in advance. In that case, how can I enable pyBK to not only be able to detect when a particular speaker is talking but also detect that there is a new user who is speaking if he has not spoken before? Does pyBK support that feature? Where can I find some reference for that?

**Pre-trained english model for diarization.**
I want to work with an already existing model and am okay using some pre-trained diarization model as long as it can detect a new speaker real-time from an audio stream. How can I find some pre-trained diarization models that I can just use right out of the box and see how well that model performs?

Thank you for your time and have a good one.

**Comment by josepatino** [comment]
Hi Shu,
apologies for the delay in my answer, and thank you for the interest in this repository. 

In response to your questions:

1. Use live audio streams instead of static audio files:
If I understand correctly you want to do online clustering on the stream of audio. Unfortunately, that functionality is not implemented in the code. Clustering is performed offline, i.e. when all data to cluster has been received and is readily available. Online clustering is feasible, but more challenging since your clustering algorithm will be making decisions on the fly based on a partial view of the identities in the conversation. This might lead to early mistakes that you could simply let be, lowering performance, or attempt to correct later on once you have accumulated more data, increasing computation needs. Another particularity, that complicates this even more when using binary key even modelling, is that the model used to derive speaker representations is also computed on the fly with all the available data. If you receive more data in an online setup, and want to re-estimate your model to obtain more robust representations, computational time will also increase. Alternatively, and thanks to the fact that diarization based on binary key modelling is very fast, you could just re-run the whole pipeline (assuming the amount of accumulated data is not outrageous as computation time will also increase with it) once every certain period of time. It all comes down to your use-case at the end. I know of some work that has been done in a master's thesis to adapt this repository to the online case which you can find in [1]. For further reading, you might want to take a look at [2] for a collection on interesting papers and tools on speaker diarization, some of which attempt to do online clustering. In some cases they rely on training data and sequential labelling to do so, which might be acceptable for you, again, depending on your use case. 

2. Number of speakers unknown in the beginning of the audio stream.
Not knowing the number of speakers in a session is usually the case in the speaker diarization task where normally no a priori information is assumed. In consequence there are two methods implemented in this repository do to this. One uses the within-class sum of squares and an elbow criterion as proposed by Delgado in [3], and the other spectral clustering and the gap between eigenvalues as in the work of Wang [4]. In an online setup, for example, you could re-estimate this number of speakers once every certain period of time to see if the hypothesis given by the algorithm has not changed.

3. Pre-trained english model for diarization
As I mention above, this particular repository relies on binary key speaker modelling, a technique which is independent of training data in its application to speaker diarization. However if a pre-trained model is explicitly what you are after, and in particular if you are interested in learning more about speaker diarization, I would recommend you take a good look to Hervé Bredin's pyannote-audio repository [5]. It is loaded with resources for training/pre-trained neural models, visualisation tools, metrics, and standardised database manipulation interfaces and good documentation, which I think you might find of use and will help you establish good practices if you plan on working in this, or related tasks, in the long-term. 

I hope I was of help,
best regards,
Jose

[1] https://github.com/henryph/vba_project/blob/master/3035349015.pdf
[2] https://github.com/wq2012/awesome-diarization
[3] Delgado, Héctor, et al. "Novel clustering selection criterion for fast binary key speaker diarization." INTERSPEECH, 2015.
[4] Wang, Quan, et al. "Speaker diarization with LSTM." 2018 IEEE International Conference on Acoustics, Speech and Signal Processing (ICASSP). IEEE, 2018.
[5] https://github.com/pyannote/pyannote-audio
